<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Complete Responsive Online Boot Store Website Design Tutorial</title>

    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />

    <!-- font awesome cdn link  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="css/styleindex.css">

</head>
<body>
    
<!-- header section starts  -->

<header class="header">

    <div class="header-1">

        <a href="#" class="logo"> <i class="fas fa-book"></i> CSTE Library </a>

        <div class="icons">
            <div id="search-btn" class="fas fa-search"></div>
           <a href="login.php"><div id="login-btn" class="fas fa-user"> Login </div></a> 
        </div>

    </div>

</header>

<!-- header section ends -->

<!-- bottom navbar  -->

<!-- login form  -->

<div class="login-form-container">

    <div id="close-login-btn" class="fas fa-times"></div>

</div>

<!-- home section starts  -->

<section class="home" id="home">

    <div class="row">

        <div class="content">
            <h3> Welcome to Our Library!</h3>
            <p>A library is a collection of materials, books or media that are easily accessible for use and not just for display purposes. It is responsible for housing updated information in order to meet the user's needs on a daily basis.</p>
        </div>

        <div class="swiper books-slider">
            <div class="swiper-wrapper">
                <a href="#" class="swiper-slide"><img src="images/indeximage/se.png" alt=""></a>
                <a href="#" class="swiper-slide"><img src="images/indeximage/cn.jpg" alt=""></a>
                <a href="#" class="swiper-slide"><img src="images/indeximage/we.jpg" alt=""></a>
                <a href="#" class="swiper-slide"><img src="images/indeximage/python.jpg" alt=""></a>
                <a href="#" class="swiper-slide"><img src="images/indeximage/wc.jpg" alt=""></a>
                <a href="#" class="swiper-slide"><img src="images/indeximage/programc.jpg" alt=""></a>
            </div>
            <img src="images/indeximage/stand.png" class="stand" alt="">
        </div>

    </div>

</section>

<!-- home section ense  -->

<section class="footer">

    <div class="box-container">

        



        <div class="box">
            <h3>contact us</h3>
            <a href="#"> <i class="fas fa-phone"></i> +88031456322 </a>
            <a href="#"> <i class="fas fa-phone"></i> +8801719856333 </a>
            <a href="#"> <i class="fas fa-envelope"></i> shobnom0113@student.nstu.edu.bd </a>
        </div>
        
    </div>

    <div class="share">
        <a href="https://www.facebook.com/groups/csteallbatch/" class="fab fa-facebook-f"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-linkedin"></a>
        <a href="https://www.youtube.com/channel/UC5SnfBf_3plTZLKcqbl3yhA/" class="fab fa-youtube"></a>
    </div>

    <div class="credit"> created by <span>Shobnom Mushtary</span> </div>

</section>

<!-- footer section ends -->

<!-- loader  -->















<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>

<!-- custom js file link  -->
<script src="js/scriptindex.js"></script>

</body>
</html>